/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.29.3
 * source: esp_rmaker_chal_resp.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace rmaker_misc {
    export enum RMakerMiscStatus {
        Success = 0,
        Fail = 1,
        InvalidParam = 2
    }
    export enum RMakerMiscMsgType {
        TypeCmdChallengeResponse = 0,
        TypeRespChallengeResponse = 1,
        TypeCmdGetNodeID = 2,
        TypeRespGetNodeID = 3
    }
    export class CmdCRPayload extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            payload?: Uint8Array;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("payload" in data && data.payload != undefined) {
                    this.payload = data.payload;
                }
            }
        }
        get payload() {
            return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array(0)) as Uint8Array;
        }
        set payload(value: Uint8Array) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            payload?: Uint8Array;
        }): CmdCRPayload {
            const message = new CmdCRPayload({});
            if (data.payload != null) {
                message.payload = data.payload;
            }
            return message;
        }
        toObject() {
            const data: {
                payload?: Uint8Array;
            } = {};
            if (this.payload != null) {
                data.payload = this.payload;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.payload.length)
                writer.writeBytes(1, this.payload);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CmdCRPayload {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CmdCRPayload();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.payload = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CmdCRPayload {
            return CmdCRPayload.deserialize(bytes);
        }
    }
    export class RespCRPayload extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            payload?: Uint8Array;
            node_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("payload" in data && data.payload != undefined) {
                    this.payload = data.payload;
                }
                if ("node_id" in data && data.node_id != undefined) {
                    this.node_id = data.node_id;
                }
            }
        }
        get payload() {
            return pb_1.Message.getFieldWithDefault(this, 1, new Uint8Array(0)) as Uint8Array;
        }
        set payload(value: Uint8Array) {
            pb_1.Message.setField(this, 1, value);
        }
        get node_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set node_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            payload?: Uint8Array;
            node_id?: string;
        }): RespCRPayload {
            const message = new RespCRPayload({});
            if (data.payload != null) {
                message.payload = data.payload;
            }
            if (data.node_id != null) {
                message.node_id = data.node_id;
            }
            return message;
        }
        toObject() {
            const data: {
                payload?: Uint8Array;
                node_id?: string;
            } = {};
            if (this.payload != null) {
                data.payload = this.payload;
            }
            if (this.node_id != null) {
                data.node_id = this.node_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.payload.length)
                writer.writeBytes(1, this.payload);
            if (this.node_id.length)
                writer.writeString(2, this.node_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RespCRPayload {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RespCRPayload();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.payload = reader.readBytes();
                        break;
                    case 2:
                        message.node_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RespCRPayload {
            return RespCRPayload.deserialize(bytes);
        }
    }
    export class CmdGetNodeIDPayload extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): CmdGetNodeIDPayload {
            const message = new CmdGetNodeIDPayload({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CmdGetNodeIDPayload {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CmdGetNodeIDPayload();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CmdGetNodeIDPayload {
            return CmdGetNodeIDPayload.deserialize(bytes);
        }
    }
    export class RespGetNodeIDPayload extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            node_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("node_id" in data && data.node_id != undefined) {
                    this.node_id = data.node_id;
                }
            }
        }
        get node_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set node_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            node_id?: string;
        }): RespGetNodeIDPayload {
            const message = new RespGetNodeIDPayload({});
            if (data.node_id != null) {
                message.node_id = data.node_id;
            }
            return message;
        }
        toObject() {
            const data: {
                node_id?: string;
            } = {};
            if (this.node_id != null) {
                data.node_id = this.node_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.node_id.length)
                writer.writeString(1, this.node_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RespGetNodeIDPayload {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RespGetNodeIDPayload();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.node_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RespGetNodeIDPayload {
            return RespGetNodeIDPayload.deserialize(bytes);
        }
    }
    export class RMakerMiscPayload extends pb_1.Message {
        #one_of_decls: number[][] = [[10, 11, 12, 13]];
        constructor(data?: any[] | ({
            msg?: RMakerMiscMsgType;
            status?: RMakerMiscStatus;
        } & (({
            cmdChallengeResponsePayload?: CmdCRPayload;
            respChallengeResponsePayload?: never;
            cmdGetNodeIDPayload?: never;
            respGetNodeIDPayload?: never;
        } | {
            cmdChallengeResponsePayload?: never;
            respChallengeResponsePayload?: RespCRPayload;
            cmdGetNodeIDPayload?: never;
            respGetNodeIDPayload?: never;
        } | {
            cmdChallengeResponsePayload?: never;
            respChallengeResponsePayload?: never;
            cmdGetNodeIDPayload?: CmdGetNodeIDPayload;
            respGetNodeIDPayload?: never;
        } | {
            cmdChallengeResponsePayload?: never;
            respChallengeResponsePayload?: never;
            cmdGetNodeIDPayload?: never;
            respGetNodeIDPayload?: RespGetNodeIDPayload;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("msg" in data && data.msg != undefined) {
                    this.msg = data.msg;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("cmdChallengeResponsePayload" in data && data.cmdChallengeResponsePayload != undefined) {
                    this.cmdChallengeResponsePayload = data.cmdChallengeResponsePayload;
                }
                if ("respChallengeResponsePayload" in data && data.respChallengeResponsePayload != undefined) {
                    this.respChallengeResponsePayload = data.respChallengeResponsePayload;
                }
                if ("cmdGetNodeIDPayload" in data && data.cmdGetNodeIDPayload != undefined) {
                    this.cmdGetNodeIDPayload = data.cmdGetNodeIDPayload;
                }
                if ("respGetNodeIDPayload" in data && data.respGetNodeIDPayload != undefined) {
                    this.respGetNodeIDPayload = data.respGetNodeIDPayload;
                }
            }
        }
        get msg() {
            return pb_1.Message.getFieldWithDefault(this, 1, RMakerMiscMsgType.TypeCmdChallengeResponse) as RMakerMiscMsgType;
        }
        set msg(value: RMakerMiscMsgType) {
            pb_1.Message.setField(this, 1, value);
        }
        get status() {
            return pb_1.Message.getFieldWithDefault(this, 2, RMakerMiscStatus.Success) as RMakerMiscStatus;
        }
        set status(value: RMakerMiscStatus) {
            pb_1.Message.setField(this, 2, value);
        }
        get cmdChallengeResponsePayload() {
            return pb_1.Message.getWrapperField(this, CmdCRPayload, 10) as CmdCRPayload;
        }
        set cmdChallengeResponsePayload(value: CmdCRPayload) {
            pb_1.Message.setOneofWrapperField(this, 10, this.#one_of_decls[0], value);
        }
        get has_cmdChallengeResponsePayload() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get respChallengeResponsePayload() {
            return pb_1.Message.getWrapperField(this, RespCRPayload, 11) as RespCRPayload;
        }
        set respChallengeResponsePayload(value: RespCRPayload) {
            pb_1.Message.setOneofWrapperField(this, 11, this.#one_of_decls[0], value);
        }
        get has_respChallengeResponsePayload() {
            return pb_1.Message.getField(this, 11) != null;
        }
        get cmdGetNodeIDPayload() {
            return pb_1.Message.getWrapperField(this, CmdGetNodeIDPayload, 12) as CmdGetNodeIDPayload;
        }
        set cmdGetNodeIDPayload(value: CmdGetNodeIDPayload) {
            pb_1.Message.setOneofWrapperField(this, 12, this.#one_of_decls[0], value);
        }
        get has_cmdGetNodeIDPayload() {
            return pb_1.Message.getField(this, 12) != null;
        }
        get respGetNodeIDPayload() {
            return pb_1.Message.getWrapperField(this, RespGetNodeIDPayload, 13) as RespGetNodeIDPayload;
        }
        set respGetNodeIDPayload(value: RespGetNodeIDPayload) {
            pb_1.Message.setOneofWrapperField(this, 13, this.#one_of_decls[0], value);
        }
        get has_respGetNodeIDPayload() {
            return pb_1.Message.getField(this, 13) != null;
        }
        get payload() {
            const cases: {
                [index: number]: "none" | "cmdChallengeResponsePayload" | "respChallengeResponsePayload" | "cmdGetNodeIDPayload" | "respGetNodeIDPayload";
            } = {
                0: "none",
                10: "cmdChallengeResponsePayload",
                11: "respChallengeResponsePayload",
                12: "cmdGetNodeIDPayload",
                13: "respGetNodeIDPayload"
            };
            return cases[pb_1.Message.computeOneofCase(this, [10, 11, 12, 13])];
        }
        static fromObject(data: {
            msg?: RMakerMiscMsgType;
            status?: RMakerMiscStatus;
            cmdChallengeResponsePayload?: ReturnType<typeof CmdCRPayload.prototype.toObject>;
            respChallengeResponsePayload?: ReturnType<typeof RespCRPayload.prototype.toObject>;
            cmdGetNodeIDPayload?: ReturnType<typeof CmdGetNodeIDPayload.prototype.toObject>;
            respGetNodeIDPayload?: ReturnType<typeof RespGetNodeIDPayload.prototype.toObject>;
        }): RMakerMiscPayload {
            const message = new RMakerMiscPayload({});
            if (data.msg != null) {
                message.msg = data.msg;
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.cmdChallengeResponsePayload != null) {
                message.cmdChallengeResponsePayload = CmdCRPayload.fromObject(data.cmdChallengeResponsePayload);
            }
            if (data.respChallengeResponsePayload != null) {
                message.respChallengeResponsePayload = RespCRPayload.fromObject(data.respChallengeResponsePayload);
            }
            if (data.cmdGetNodeIDPayload != null) {
                message.cmdGetNodeIDPayload = CmdGetNodeIDPayload.fromObject(data.cmdGetNodeIDPayload);
            }
            if (data.respGetNodeIDPayload != null) {
                message.respGetNodeIDPayload = RespGetNodeIDPayload.fromObject(data.respGetNodeIDPayload);
            }
            return message;
        }
        toObject() {
            const data: {
                msg?: RMakerMiscMsgType;
                status?: RMakerMiscStatus;
                cmdChallengeResponsePayload?: ReturnType<typeof CmdCRPayload.prototype.toObject>;
                respChallengeResponsePayload?: ReturnType<typeof RespCRPayload.prototype.toObject>;
                cmdGetNodeIDPayload?: ReturnType<typeof CmdGetNodeIDPayload.prototype.toObject>;
                respGetNodeIDPayload?: ReturnType<typeof RespGetNodeIDPayload.prototype.toObject>;
            } = {};
            if (this.msg != null) {
                data.msg = this.msg;
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.cmdChallengeResponsePayload != null) {
                data.cmdChallengeResponsePayload = this.cmdChallengeResponsePayload.toObject();
            }
            if (this.respChallengeResponsePayload != null) {
                data.respChallengeResponsePayload = this.respChallengeResponsePayload.toObject();
            }
            if (this.cmdGetNodeIDPayload != null) {
                data.cmdGetNodeIDPayload = this.cmdGetNodeIDPayload.toObject();
            }
            if (this.respGetNodeIDPayload != null) {
                data.respGetNodeIDPayload = this.respGetNodeIDPayload.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.msg != RMakerMiscMsgType.TypeCmdChallengeResponse)
                writer.writeEnum(1, this.msg);
            if (this.status != RMakerMiscStatus.Success)
                writer.writeEnum(2, this.status);
            if (this.has_cmdChallengeResponsePayload)
                writer.writeMessage(10, this.cmdChallengeResponsePayload, () => this.cmdChallengeResponsePayload.serialize(writer));
            if (this.has_respChallengeResponsePayload)
                writer.writeMessage(11, this.respChallengeResponsePayload, () => this.respChallengeResponsePayload.serialize(writer));
            if (this.has_cmdGetNodeIDPayload)
                writer.writeMessage(12, this.cmdGetNodeIDPayload, () => this.cmdGetNodeIDPayload.serialize(writer));
            if (this.has_respGetNodeIDPayload)
                writer.writeMessage(13, this.respGetNodeIDPayload, () => this.respGetNodeIDPayload.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): RMakerMiscPayload {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new RMakerMiscPayload();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.msg = reader.readEnum();
                        break;
                    case 2:
                        message.status = reader.readEnum();
                        break;
                    case 10:
                        reader.readMessage(message.cmdChallengeResponsePayload, () => message.cmdChallengeResponsePayload = CmdCRPayload.deserialize(reader));
                        break;
                    case 11:
                        reader.readMessage(message.respChallengeResponsePayload, () => message.respChallengeResponsePayload = RespCRPayload.deserialize(reader));
                        break;
                    case 12:
                        reader.readMessage(message.cmdGetNodeIDPayload, () => message.cmdGetNodeIDPayload = CmdGetNodeIDPayload.deserialize(reader));
                        break;
                    case 13:
                        reader.readMessage(message.respGetNodeIDPayload, () => message.respGetNodeIDPayload = RespGetNodeIDPayload.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): RMakerMiscPayload {
            return RMakerMiscPayload.deserialize(bytes);
        }
    }
}
