/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

import { ESPRMNeoBase } from "../../ESPRMNeoBase";
import { ESPSigV4APIManager } from "../ESPSigV4APIManager";
import {
  CLAIM_MAC_HEX_LENGTHS,
  CLAIM_MAC_SEPARATORS,
  ClaimCapabilities,
  ClaimCapabilityPolicies,
  ClaimEndpoints,
  ClaimErrorCodes,
} from "../../utils/constants";
import { ESPClaimError } from "../../utils/error/ESPClaimError";
import { Logger } from "../../utils/logger";

const logger = new Logger("ClaimingHelper");

/**
 * Request body for `POST /v1/claim/initiate`. The device's own claim-start fields
 * are forwarded alongside `mac_addr`.
 */
export interface ClaimInitiateRequest extends Record<string, unknown> {
  /** Device MAC, 12 or 16 hex characters, separators stripped. */
  mac_addr: string;
}

/** Response body from `POST /v1/claim/initiate`. */
export interface ClaimInitiateResponse {
  /** 16 uppercase hex characters. Also the IoT Thing name and MQTT client id. */
  node_id: string;
  /** Present only under the `device_attested` variant; not yet implemented. */
  challenge?: string;
}

/**
 * The device's own claim payload, forwarded whole to verify. Firmware sends
 * request flags alongside the CSR, so extracting only `csr` would drop them.
 */
export interface ClaimDevicePayload extends Record<string, unknown> {
  /** PEM `CERTIFICATE REQUEST` generated by the device. */
  csr: string;
}

/** Request body for `POST /v1/claim/verify`. */
export interface ClaimVerifyRequest extends Record<string, unknown> {
  /** Same device MAC as initiate; selects the reservation to resolve. */
  mac_addr: string;
  /** PEM `CERTIFICATE REQUEST`, ECDSA P-256, max 8 KB. */
  csr: string;
  /** Extra IoT policies to attach, e.g. `s3`, `kvs`, `bridge`. */
  capabilities?: string[];
}

/** Response body from `POST /v1/claim/verify`. */
export interface ClaimVerifyResponse {
  node_id: string;
  /** Device leaf certificate. Only the claiming service can issue this. */
  certificate: string;
  /**
   * Broker host for the device. Optional by design — the claiming service omits
   * it because the app already knows the deployment's broker, so the SDK fills it
   * in from `iotEndpoint` before forwarding the payload to the device.
   */
  mqtt_host?: string;
  /** Issuing CA, for the device's trust store. */
  ca_certificate?: string;
  /** Credentials-provider endpoint. Forwarded, but the firmware ignores it. */
  mqtt_cred_host?: string;
}

/**
 * Assisted-claiming cloud calls.
 *
 * Both routes live on the deployment's main API and are IAM-authorized like their
 * neighbours, so they go through {@link ESPSigV4APIManager} and are SigV4-signed
 * against `baseUrl`. A Cognito JWT is rejected there with
 * `403 Invalid key=value pair (missing equal-sign) in Authorization header`.
 *
 * Both calls are independently retryable: initiate is idempotent per device and
 * caller, and verify replaces the device's certificate rather than duplicating
 * the node.
 */
export class ClaimingHelper {
  /**
   * Normalizes a device MAC: separators stripped and upper-cased, so every
   * spelling of one address resolves to the same reservation.
   *
   * @param raw - MAC as reported by the device
   * @returns Normalized MAC
   * @throws ESPClaimError when the value is not 12 or 16 hex characters
   */
  static normalizeMacAddress(raw: string): string {
    const mac = raw.trim().replace(CLAIM_MAC_SEPARATORS, "").toUpperCase();
    const isHex = /^[0-9A-F]+$/.test(mac);
    const hasValidLength = (
      CLAIM_MAC_HEX_LENGTHS as readonly number[]
    ).includes(mac.length);

    if (!isHex || !hasValidLength) {
      logger.error("device MAC is not a valid claiming MAC", {
        length: mac.length,
        isHex,
      });
      throw new ESPClaimError(ClaimErrorCodes.DEVICE_MAC_UNAVAILABLE);
    }
    return mac;
  }

  /**
   * Reduces a broker endpoint to the bare host the device stores. The device
   * keeps host and port separately, so a scheme, path or `:port` would be
   * persisted verbatim into the factory partition and fail to resolve.
   *
   * @param raw - Broker endpoint in any form
   * @returns Host only, or "" when nothing usable remains
   */
  static normalizeMqttHost(raw: string): string {
    return raw
      .trim()
      .replace(/^[a-z][a-z0-9+.-]*:\/\//i, "") // scheme
      .replace(/\/.*$/, "") // path
      .replace(/:\d+$/, "") // port
      .trim();
  }

  /**
   * Issues a SigV4-signed claiming POST. Signing, credential refresh and retry
   * come from {@link ESPSigV4APIManager}, which also attaches a failed call's
   * `{ message }` body to the thrown error as `responseData`.
   *
   * @param path - Claiming path, e.g. `/v1/claim/initiate`
   * @param body - JSON request body
   * @param claimId - Correlation id for this claim attempt
   * @returns Parsed JSON response
   * @throws ESPClaimError when the SDK is unconfigured or the call fails
   */
  private static async postClaim<T>(
    path: string,
    body: Record<string, unknown>,
    claimId: string
  ): Promise<T> {
    let api: ESPSigV4APIManager;
    try {
      api = ESPSigV4APIManager.getInstance();
    } catch {
      logger.error("claiming unavailable: SDK is not configured", { claimId });
      throw new ESPClaimError(ClaimErrorCodes.CLAIM_API_NOT_CONFIGURED);
    }

    try {
      return await api.post<T>(path, body);
    } catch (error) {
      const failure = error as {
        status?: number;
        responseData?: { message?: unknown };
      };
      const message = failure.responseData?.message;
      const reason =
        typeof message === "string" && message.trim()
          ? message.trim()
          : error instanceof Error
            ? error.message
            : String(error);

      logger.error("claim request failed", {
        claimId,
        path,
        httpStatus: failure.status,
        reason,
      });
      throw new ESPClaimError(
        ClaimErrorCodes.CLAIM_API_FAILED,
        failure.status ? `HTTP ${failure.status}: ${reason}` : reason
      );
    }
  }

  /**
   * Assigns a node ID to the device's MAC address.
   *
   * `POST /v1/claim/initiate` — 201 for a new reservation, 200 when one already
   * existed, returning the same node ID either way. That idempotency is what lets
   * a factory-erased device come back as the same node.
   *
   * @param macAddress - Device MAC, normalized before sending
   * @param devicePayload - The device's claim-start payload, forwarded whole
   * @param claimId - Correlation id for this claim attempt
   * @returns The assigned node ID and any attestation challenge
   * @throws ESPClaimError when the MAC is invalid or the call fails
   */
  static async initiateClaim(
    macAddress: string,
    devicePayload: Record<string, unknown> = {},
    claimId = ""
  ): Promise<ClaimInitiateResponse> {
    const request: ClaimInitiateRequest = {
      ...devicePayload,
      // Last, so a raw MAC in the device payload cannot shadow the normalized one.
      mac_addr: this.normalizeMacAddress(macAddress),
    };

    const response = await this.postClaim<ClaimInitiateResponse>(
      ClaimEndpoints.CLAIM_INITIATE,
      request,
      claimId
    );

    if (!response?.node_id) {
      logger.error("claim initiate returned no node_id", { claimId });
      throw new ESPClaimError(
        ClaimErrorCodes.CLAIM_API_FAILED,
        "response contained no node_id"
      );
    }
    return response;
  }

  /**
   * Exchanges the device's CSR for a signed certificate.
   *
   * `POST /v1/claim/verify` — the CSR's subject is ignored; the certificate's
   * Common Name comes from the reservation. Called again after a factory erase, it
   * issues a new certificate and deactivates the previous one, node ID unchanged.
   *
   * @param macAddress - Same device MAC as initiate
   * @param devicePayload - The device's claim payload, forwarded whole
   * @param claimCapability - Optional capability, mapped to extra IoT policies
   * @param claimId - Correlation id for this claim attempt
   * @returns The claim response, with `mqtt_host` resolved for the device
   * @throws ESPClaimError when the call fails or no certificate is returned
   */
  static async verifyClaim(
    macAddress: string,
    devicePayload: ClaimDevicePayload,
    claimCapability?: ClaimCapabilities,
    claimId = ""
  ): Promise<ClaimVerifyResponse> {
    const request: ClaimVerifyRequest = {
      ...devicePayload,
      // Last, so a raw MAC in the device payload cannot shadow the normalized one.
      mac_addr: this.normalizeMacAddress(macAddress),
    };

    const policies = claimCapability
      ? ClaimCapabilityPolicies[claimCapability]
      : undefined;
    if (policies?.length) {
      request.capabilities = [...policies];
    } else if (claimCapability) {
      // Omitted rather than guessed — see ClaimCapabilityPolicies.
      logger.warn("claim capability has no mapped IoT policies; sending none", {
        claimId,
        claimCapability,
      });
    }

    const response = await this.postClaim<ClaimVerifyResponse>(
      ClaimEndpoints.CLAIM_VERIFY,
      request,
      claimId
    );

    if (!response?.certificate) {
      logger.error("claim verify returned no certificate", {
        claimId,
        received: response ? Object.keys(response) : null,
      });
      throw new ESPClaimError(
        ClaimErrorCodes.CLAIM_API_FAILED,
        "response is missing certificate"
      );
    }

    return {
      ...response,
      mqtt_host: this.resolveDeviceMqttHost(response, claimId),
    };
  }

  /**
   * Resolves the broker host to hand the device, normalized to a bare host.
   *
   * The app owns this value: the claiming service omits it because the app
   * already learned the deployment's broker from its config, so the configured
   * `iotEndpoint` is the normal source and is correct by construction — it is the
   * broker of the deployment that just issued this certificate. A `mqtt_host` in
   * the response still wins if one is ever sent.
   *
   * Resolved before streaming because the device validates the reassembled
   * payload only on its final fragment: an absent host surfaces there as a
   * rejected certificate fragment, with nothing pointing at MQTT.
   *
   * @param response - Parsed claim/verify response
   * @param claimId - Correlation id for this claim attempt
   * @returns Bare broker host
   * @throws ESPClaimError when neither source yields a usable host
   */
  private static resolveDeviceMqttHost(
    response: ClaimVerifyResponse,
    claimId: string
  ): string {
    const fromService = this.normalizeMqttHost(response.mqtt_host ?? "");
    if (fromService) {
      return fromService;
    }

    let configured: string | undefined;
    try {
      configured = ESPRMNeoBase.getConfig().iotEndpoint;
    } catch {
      configured = undefined;
    }
    const fromConfig = this.normalizeMqttHost(configured ?? "");

    if (!fromConfig) {
      logger.error("no mqtt_host for the device", {
        claimId,
        fromResponse: response.mqtt_host ?? null,
        configuredIotEndpoint: configured ?? null,
      });
      throw new ESPClaimError(
        ClaimErrorCodes.CLAIM_API_FAILED,
        "no mqtt_host available: the claim response omitted it and no iotEndpoint is configured"
      );
    }
    return fromConfig;
  }
}
